baseURL = "https://filipnikolovski.com/"
languageCode = "en-us"
title = "Filip Nikolovski"
theme = "smol"
enableRobotsTXT=true

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "Filip Nikolovski"

# Parameters
[params]
    subtitle = "A blog about programming, technology and open-source stuff."
    description = "A blog about programming, technology and open-source stuff."
    dateFmt = "02.01.2006 15:04"
    author = "Filip Nikolovski"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 4

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/FilipNikolovski"
        weight = 1

  [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/fffiiicc"
        weight = 2

  [[menu.footer]]
        name = "RSS"
        url = "/index.xml"
        weight = 3

  [[menu.footer]]
        name = "Powered by Netlify"
        url = "https://www.netlify.com/"
        weight = 4
